- name: Deploy relay
  hosts: relays
  gather_facts: true
  become: false

  vars:
    uv_binary_path: "{{ ansible_user_dir }}/.local/bin/uv"
    repo_url: "git@github.com:barkm/birdhouse.git"
    repo_dest: "{{ ansible_user_dir }}/birdhouse"
    repo_version: "main"

  pre_tasks:
    - include_tasks: ../tasks/uv.yaml
    - include_tasks: ../tasks/git.yaml

  tasks:
    - name: Install relay server
      ansible.builtin.command: ./relay.sh install
      args:
        chdir: "{{ repo_dest }}/relay"
      environment:
        PATH: "{{ uv_binary_path | dirname }}:{{ ansible_env.PATH }}"