services:
  relay:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.relay
    ports:
      - "8001"
    secrets:
      - gcp_key
    environment:
      - PORT=8001
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcp_key
      - DATABASE_URL=postgresql+psycopg://moja:moja@db:5432/moja
    env_file:
      - ./relay/.env
    networks:
      - relay_net
    depends_on:
      - db

  pi:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.pi
    ports:
      - "8000"
    environment:
      - PORT=8000
      - URL=http://pi:8000
      - REGISTER_URL=http://relay:8001/register
      - NAME=docker-birdhouse
      - TEST_STREAM=True
      - TEST_SENSOR=True
    depends_on:
      - relay
    networks:
      - relay_net

  house:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.pi
    ports:
      - "8010"
    environment:
      - PORT=8010
      - URL=http://house:8010
      - REGISTER_URL=http://relay:8001/register
      - NAME=docker-house
      - TEST_STREAM=True
      - TEST_SENSOR=True
    depends_on:
      - relay
    networks:
      - relay_net


  recorder:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.recorder
    ports:
      - "8003:8003"
    secrets:
      - gcp_key
    environment:
      - PORT=8003
      - RELAY_URL=http://relay:8001
      - RECORDING_DIR=gs://birdhouse-recordings
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcp_key
    env_file:
      - ./recorder/.env
    depends_on:
      - relay
      - pi
    networks:
      - relay_net
    
  db:
    image: postgres:17
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: moja
      POSTGRES_USER: moja
      POSTGRES_PASSWORD: moja
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - relay_net
    
  caddy:
    image: caddy:2
    volumes:
      - ./relay/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "8080:8080"
    environment:
      - DOMAIN=:8080
      - SERVER=relay:8001
    depends_on:
      - relay
    networks:
      - relay_net

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    ports:
      - "8004:8004"
    environment:
      - PORT=8004
    depends_on:
      - relay


networks:
  relay_net:
    driver: bridge

secrets:
  gcp_key:
    file: ~/.config/gcloud/application_default_credentials.json
  
volumes:
  db-data: