services:
  relay:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.relay
    ports:
      - "8001:8001"
    secrets:
      - gcp_key
    environment:
      - PORT=8001
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcp_key
      - FASTAPI_MODE=dev
      - REGISTER_URL=http://recorder:8003/register
    env_file:
      - ./relay/.env
    networks:
      - relay_net
    depends_on:
      - recorder
    develop:
      watch:
        - action: sync
          path: ./relay/
          target: /app/relay
        - action: sync
          path: ./common/
          target: /app/common


  pi:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.pi
    ports:
      - "8000"
    environment:
      - PORT=8000
      - URL=http://pi:8000
      - REGISTER_URL=http://relay:8001/register
      - NAME=birdhouse
      - TEST_STREAM=True
      - TEST_SENSOR=True
      - FASTAPI_MODE=dev
    depends_on:
      - relay
    networks:
      - relay_net
    develop:
      watch:
        - action: sync
          path: ./pi/
          target: /app/pi

  house:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.pi
    ports:
      - "8010"
    environment:
      - PORT=8010
      - URL=http://house:8010
      - REGISTER_URL=http://relay:8001/register
      - NAME=house
      - TEST_STREAM=True
      - TEST_SENSOR=True
      - FASTAPI_MODE=dev
    depends_on:
      - relay
    networks:
      - relay_net
    develop:
      watch:
        - action: sync
          path: ./pi/
          target: /app/pi


  recorder:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.recorder
    ports:
      - "8003:8003"
    secrets:
      - gcp_key
    environment:
      - PORT=8003
      - RECORDING_DIR=gs://birdhouse-recordings/dev
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcp_key
      - DATABASE_URL=postgresql+psycopg://moja:moja@host.docker.internal:5432/moja
      - FASTAPI_MODE=dev
    env_file:
      - ./recorder/.env
    depends_on:
      - relay
      - pi
    networks:
      - relay_net
    develop:
      watch:
        - action: sync
          path: ./recorder/
          target: /app/recorder
        - action: sync
          path: ./common/
          target: /app/common
    
  db:
    image: postgres:17
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./deployment/initdb:/docker-entrypoint-initdb.d
    networks:
      - relay_net
    
  caddy:
    image: caddy:2
    volumes:
      - ./relay/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "8080:8080"
    environment:
      - DOMAIN=http://localhost:8080
      - SERVER=relay:8001
    depends_on:
      - relay
    networks:
      - relay_net

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    ports:
      - "8004:8004"
    environment:
      - PORT=8004
    depends_on:
      - relay
    develop:
      watch:
        - action: sync
          path: ./web/
          target: /app


networks:
  relay_net:
    driver: bridge

secrets:
  gcp_key:
    file: ~/.config/gcloud/application_default_credentials.json

volumes:
  db-data: