- name: Deploy crontab
  hosts: pis
  gather_facts: true
  become: false

  vars:
    uv_binary_path: "{{ ansible_facts["user_dir"] }}/.local/bin/uv"
    repo_url: "git@github.com:barkm/birdhouse.git"
    repo_dest: "{{ ansible_facts["user_dir"] }}/code/birdhouse"
    repo_version: "main"

  pre_tasks:
    - include_tasks: ../tasks/git.yaml

  tasks:
    - name: Install crontab
      ansible.builtin.command: ./crontab.sh $NAME $URL
      args:
        chdir: "{{ repo_dest }}/pi"
      environment:
        NAME: "{{ lookup('env', 'NAME') }}"
        URL: "{{ lookup('env', 'REGISTER_ACCESS_URL') }}:{{ register_port }}"