- name: Install caddy
  hosts: pis
  gather_facts: true
  become: false

  vars:
    repo_url: "git@github.com:barkm/birdhouse.git"
    repo_dest: "{{ ansible_user_dir }}/code/birdhouse"
    repo_version: "main"

  pre_tasks:
    - include_tasks: tasks/git.yaml

  tasks:
    - name: Install caddy
      ansible.builtin.command: ./caddy.sh
      args:
        chdir: "{{ repo_dest }}/pi"