- name: Deploy crontab
  hosts: pis
  gather_facts: true
  become: false

  vars:
    uv_binary_path: "{{ ansible_user_dir }}/.local/bin/uv"
    repo_url: "git@github.com:barkm/birdhouse.git"
    repo_dest: "{{ ansible_user_dir }}/code/birdhouse"
    repo_version: "main"

  pre_tasks:
    - include_tasks: tasks/git.yaml

  tasks:
    - name: Install crontab
      ansible.builtin.command: ./crontab.sh $NAME $SERVER_PORT
      args:
        chdir: "{{ repo_dest }}/pi"
      environment:
        NAME: "{{ lookup('env', 'NAME') }}"
        SERVER_PORT: "{{ lookup('env', 'SERVER_PORT') }}"