name: Deploy camera server

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - pi/**
      - ansible/playbooks/pi/camera_server.yaml
      - ./github/workflows/deploy_camera_server.yaml



jobs:
  deploy:
    uses: ./.github/workflows/run_ansible.yaml
    with:
      command: uv run ansible-playbook -i ansible/inventory.yaml ansible/playbooks/pi/camera_server.yaml
    secrets: inherit