name: Deploy relay

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - relay/**
      - ansible/playbooks/relay/relay.yaml
      - ./github/workflows/deploy_relay.yaml

concurrency:
  group: relay

jobs:
  deploy:
    uses: ./.github/workflows/run_ansible.yaml
    with:
      command: uv run ansible-playbook -i ansible/inventory.yaml ansible/playbooks/relay/relay.yaml
    secrets: inherit